name: manage-azure-policy-3ffb9b4f
on:
  push:
    paths:
      - 'policies/Audit_HTTPS_only_access_for_a_Web_Application_5ef3cc87-89f3-4c8a-bbfa-76b889c386c0/**'
      - .github/workflows/manage-azure-policy-3ffb9b4f.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_3ffb9b4f}}
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Audit_HTTPS_only_access_for_a_Web_Application_5ef3cc87-89f3-4c8a-bbfa-76b889c386c0/**
